### ISSUE TITLE
translation workflow

### ISSUE THREAD

**Issue by kyzh** [rodriformiga/pixel-dungeon#1]
I love your work.
I would like to do something similar for french.

I would love to understand more of your workflow and testing methodology.
Could you maybe create a translator.md with basic information to get started?

**Comment by rodriformiga** [comment]
Hello @kyzh 
The translation into French was completed some time. Still, I updated the translation of data and I am using an online tool (www.transifex.com/pixel-dungeon/pixel-1) to facilitate translation.
Any help will be welcome.
Thank you.
