### ISSUE TITLE
Russian translation status for 1.7.2

### ISSUE THREAD

**Issue by Mikhael-Danilov** [rodriformiga/pixel-dungeon#3]
Hi, first of all i want thank you for preparation for internationalization.

My Russian translation for 1.7.2 can be considered usable ( https://github.com/NYRDS/pixel-dungeon-rus/tree/rus.19 )

But in translation process I created additional properties ( to build syntax-correct Russian phrases in combat log ) for mob's & heroes such as:
```xml
   <string name="Rat_Gender">female</string>
   <string name="Rat_Name_Objective">крысу</string>
```
And turned some string to string-arrays to correctly follow Russian syntax ( gender part ) such as:
```xml
   <string-array name = "Hunger_Hungry" >
       <item>Ты голодено.</item>
       <item>Ты голоден.</item>
       <item>Ты голодна.</item>
   </string-array>
```
Still need to deal with weapon & enchantment grammatical gender but this is different story...

Code modified too.
And merging it back will require modification for others localizations too... ( it's done in my fork for English )

So anyone interested in Russian translation for 1.7.2 source can use it.

Also I publish my fork as separate application. And going to mod it more or less independently of watabou source. So localization for versions after 1.7.2 will be out of sync.

**Comment by Mikhael-Danilov** [comment]
Forgot to mark xml in first message...

**Comment by rodriformiga** [comment]
Hi, @Mikhael-Danilov 
Thank you for report. I'll be checking in soon and putting the translation officially in the game.

;)
